### ISSUE TITLE
Not working on Android 8.0, WIndowMetrics is not available for API <30

### ISSUE THREAD

**Issue by waozixyz** [DioxusLabs/dioxus#3401]
I made a testapp using dioxus cli, the most basic one to debug on issue on an older device. and noticed that it does not work. The app immediately crashes.

Using adb logcat i could find this:

```
FATAL EXCEPTION: Thread-2
Process: com.example.Testapp, PID: 30573
java.lang.NoSuchMethodError: no non-static method "Landroid/view/WindowManagerImpl;.getCurrentWindowMetrics()Landroid/view/WindowMetrics;"

```

Get current window metrics is not available for Android 9.0 (API 28), it was introduced in API 30

Full log:

```play a backtrace
12-18 22:45:52.577 30573 30597 E AndroidRuntime: FATAL EXCEPTION: Thread-2
12-18 22:45:52.577 30573 30597 E AndroidRuntime: Process: com.example.Testapp, PID: 30573
12-18 22:45:52.577 30573 30597 E AndroidRuntime: java.lang.NoSuchMethodError: no non-static method "Landroid/view/WindowManagerImpl;.getCurrentWindowMetrics()Landroid/view/WindowMetrics;"
12-18 22:45:52.580   966  7781 W ActivityManager:   Force finishing activity com.example.Testapp/dev.dioxus.main.MainActivity
12-18 22:45:52.585   966  7781 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-18 22:45:52.598   966   986 I ActivityManager: Showing crash dialog for package com.example.Testapp u0
12-18 22:45:52.585   966  7781 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-18 22:45:52.618 30347 30347 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.mobstore.service.START pkg=com.google.android.gms }
12-18 22:45:52.631   966 30607 W DropBoxManagerService: Dropping: data_app_crash (319 > 0 bytes)
12-18 22:45:52.633   966 30607 W AES     : Exception Log handling...
12-18 22:45:52.633   966 30607 W AES     : Skipped - do not care third party apk
12-18 22:45:52.635   966   985 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-18 22:45:52.640   966   986 D ViewRootImpl[Testapp]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
12-18 22:45:52.649   966   986 V WindowManager: Changing focus from null to Window{90a0cf5 u0 Application Error: com.example.Testapp} Callers=com.android.server.wm.WindowManagerService.addWindow:1519 com.android.server.wm.Session.addToDisplay:205 android.view.ViewRootImpl.setView:783 android.view.WindowManagerGlobal.addView:356
12-18 22:45:52.649   966   986 D WindowManager: Input focus has changed to Window{90a0cf5 u0 Application Error: com.example.Testapp}
12-18 22:45:52.650   966   993 I WindowManager: Focus moving from null to Window{90a0cf5 u0 Application Error: com.example.Testapp}
12-18 22:45:52.657   487   927 I BufferQueue: [unnamed-487-2936](this:0xb0b20000,id:2936,api:0,p:-1,c:-1) BufferQueue core=(487:/system/bin/surfaceflinger)
12-18 22:45:52.657   487   927 I BufferQueueConsumer: [unnamed-487-2936](this:0xb0b20000,id:2936,api:0,p:-1,c:487) connect(C): consumer=(487:/system/bin/surfaceflinger) controlledByApp=false
12-18 22:45:52.657   487   927 I BufferQueueConsumer: [unnamed-487-2936](this:0xb0b20000,id:2936,api:0,p:-1,c:487) setConsumerName: unnamed-487-2936
12-18 22:45:52.657   487   927 I BufferQueueConsumer: [Application Error: com.example.Testapp#0](this:0xb0b20000,id:2936,api:0,p:-1,c:487) setConsumerName: Application Error: com.example.Testapp#0
12-18 22:45:52.657   487   927 I BufferQueueConsumer: [Application Error: com.example.Testapp#0](this:0xb0b20000,id:2936,api:0,p:-1,c:487) setDefaultBufferSize: width=795 height=455
12-18 22:45:52.659   966   986 D Surface : Surface::allocateBuffers(this=0x7deff800)
12-18 22:45:52.659   966  9116 I OpenGLRenderer: Initialized EGL, version 1.4
12-18 22:45:52.659   966  9116 D OpenGLRenderer: Swap behavior 2
12-18 22:45:52.676 17795 30610 E DropBoxUtil: [AppErrors] null InputStream [CONTEXT service_id=254 ]
12-18 22:45:52.676 17795 30610 E DropBoxUtil: java.io.IOException: null InputStream
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at czre.b(:com.google.android.gms@244738009@24.47.38 (100300-705893532):184)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at czpm.l(:com.google.android.gms@244738009@24.47.38 (100300-705893532):7)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at czpg.apply(:com.google.android.gms@244738009@24.47.38 (100300-705893532):39)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at sxy.apply(:com.google.android.gms@244738009@24.47.38 (100300-705893532):5)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at syk.apply(:com.google.android.gms@244738009@24.47.38 (100300-705893532):45)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvht.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):3)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at eetn.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdh.d(:com.google.android.gms@244738009@24.47.38 (100300-705893532):3)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdj.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):38)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emev.execute(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.h(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.hf(:com.google.android.gms@244738009@24.47.38 (100300-705893532):40)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdj.g(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvhl.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):20)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at eetm.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfc.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):20)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emhf.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):3)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emgg.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):19)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emhh.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):5)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfe.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):53)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emev.execute(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfe.execute(:com.google.android.gms@244738009@24.47.38 (100300-705893532):76)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.h(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.hf(:com.google.android.gms@244738009@24.47.38 (100300-705893532):40)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfg.b(:com.google.android.gms@244738009@24.47.38 (100300-705893532):33)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvhp.i(:com.google.android.gms@244738009@24.47.38 (100300-705893532):18)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvhx.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):10)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at eetn.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdh.d(:com.google.android.gms@244738009@24.47.38 (100300-705893532):3)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdj.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):38)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emev.execute(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.h(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.hf(:com.google.android.gms@244738009@24.47.38 (100300-705893532):40)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdj.g(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvhv.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):20)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at eetm.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfc.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):20)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emhf.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):3)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emgg.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):19)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emhh.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):5)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfe.run(:com.google.android.gms@244738009@24.47.38 (100300-705893532):53)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emev.execute(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfe.execute(:com.google.android.gms@244738009@24.47.38 (100300-705893532):76)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.h(:com.google.android.gms@244738009@24.47.38 (100300-705893532):1)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emdd.hf(:com.google.android.gms@244738009@24.47.38 (100300-705893532):40)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at emfg.b(:com.google.android.gms@244738009@24.47.38 (100300-705893532):33)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvid.c(:com.google.android.gms@244738009@24.47.38 (100300-705893532):56)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at dvid.b(:com.google.android.gms@244738009@24.47.38 (100300-705893532):10)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):379)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at oqe.handleMessage(:com.google.android.gms@244738009@24.47.38 (100300-705893532):7)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at android.os.Looper.loop(Looper.java:193)
12-18 22:45:52.676 17795 30610 E DropBoxUtil: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: [AppDoctor] null InputStream [CONTEXT service_id=254 ]
12-18 22:45:52.682 17795 30610 E DropBoxUtil: java.io.IOException: null InputStream
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at czre.b(:com.google.android.gms@244738009@24.47.38 (100300-705893532):184)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at czpm.l(:com.google.android.gms@244738009@24.47.38 (100300-705893532):7)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at czpe.apply(:com.google.android.gms@244738009@24.47.38 (100300-705893532):37)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@244738009@24.47.38 (100300-705893532):479)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@244738009@24.47.38 (100300-705893532):13)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at oqe.handleMessage(:com.google.android.gms@244738009@24.47.38 (100300-705893532):7)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at android.os.Looper.loop(Looper.java:193)
12-18 22:45:52.682 17795 30610 E DropBoxUtil: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-18 22:45:52.695   966  9116 D Surface : Surface::connect(this=0x7deff800,api=1)
12-18 22:45:52.695   487   927 I BufferQueueProducer: [Application Error: com.example.Testapp#0](this:0xb0b20000,id:2936,api:1,p:966,c:487) connect(P): api=1 producer=(966:system_server) producerControlledByApp=false
12-18 22:45:52.752 30573 30573 W example.Testap: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
12-18 22:45:52.754 30573 30573 W example.Testap: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
12-18 22:45:52.766   966   986 W Looper  : Slow dispatch took 102ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@8b88d33 m=0
12-18 22:45:52.771 30573 30573 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@99c7904
12-18 22:45:52.771 30573 30573 D OpenGLRenderer: Skia GL Pipeline
12-18 22:45:52.792 30573 30573 D ViewRootImpl[MainActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
12-18 22:45:52.795   487   536 I SurfaceFlinger: [SF client] NEW(0xb02a5d80) for (966:system_server)
12-18 22:45:52.799 30573 30573 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@278a7b3, this = DecorView@7ea2170[MainActivity]
12-18 22:45:52.804   966  1040 D View    : [Warning] assignParent to null: this = DecorView@42e60db[Testapp]
12-18 22:45:52.804   966  1861 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-18 22:45:52.805   966  1861 V WindowManager: Set focused app to: AppWindowToken{64593a5 token=Token{cb05d9c ActivityRecord{1b6c90f u0 bitpit.launcher/.ui.HomeActivity t2}}} old focus=AppWindowToken{c246296 token=Token{fb83db1 ActivityRecord{3b27858 u0 com.example.Testapp/dev.dioxus.main.MainActivity t10972}}} moveFocusNow=true
12-18 22:45:52.804   966  1861 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-18 22:45:52.806   466   493 I vendor.mediatek.hardware.power@2.0-impl: notifyAppState pack:bitpit.launcher, act:bitpit.launcher.ui.HomeActivity, pid:17664, state:1
12-18 22:45:52.807   466   492 I libPowerHal: [perfNotifyAppState] foreground:bitpit.launcher, pid:17664
12-18 22:45:52.817   966  1861 D Surface : Surface::disconnect(this=0x62bb3000,api=2)
12-18 22:45:52.817   487   534 I BufferQueueProducer: [Splash Screen com.example.Testapp#0](this:0xb0298000,id:293

```

**Comment by waozixyz** [comment]
![Screenshot_20241219-012713.png](https://github.com/user-attachments/assets/efdfe292-afee-4d0e-9e54-1dfcb34bf724)

**Comment by waozixyz** [comment]
I guess this is not a dioxus issue but a tao issue that is used underneath, I found the function in the tao source code if this is really the cause of the constant crash of any dioxus app attempting to run on an older model

![Screenshot_20241219-015417](https://github.com/user-attachments/assets/d9f86197-7565-418c-a8f8-1737cb7af2ce)

**Comment by jkelleyrtp** [comment]
Android 9 is quite old...
```
Final security update
The final security update for Android 9 was released on January 4, 2022.
```

We might need to upgrade our version of tao - maybe tauri updated tao to not crash?

Can you try tao out but with the same version Dioxus uses? There's also a chance we enable features that shoudn't be enabled and/or are hitting a codepath that tauri doesn't.

**Comment by DogeDark** [comment]
@jkelleyrtp I use Android 9 and didn't have this issue before the release. The WindowMetric API call in Tao hasn't been changed in two years.

**Comment by waozixyz** [comment]
@DogeDark you are right its not the windowmetric causing the issue, AndroidX is enabled os the backport shouldn't be an issue, something else is causing the crash...

**Comment by waozixyz** [comment]
@jkelleyrtp that was also my next thought, i'll try it out

**Comment by jkelleyrtp** [comment]
There's a chance we need to enable some compat flag somewhere that got "lost in translation" from our android rig to production. I thought androidx was that, but I vaugely remember another.

**Comment by waozixyz** [comment]
I cloned dioxus and changed the version of tao to 0.30.8, which was the version which worked fine with tauri, and i also tried version 0.31.0 of tao. So i don't think the issue is the tao version itself.

the only difference i can tell in the tao dependency is that tauri uses default_features = false

```tao = { version = "0.31.0", default-features = false, features = ["rwh_06"] }```

**Comment by waozixyz** [comment]
But the error is the adb logcat is different!

Using tao 0.30.0 current dioxus default:
```
12-20 11:38:00.870 16116 16185 I RustStdoutStderr: thread '<unnamed>' panicked at /home/wao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.30.0/src/platform_impl/android/mod.rs:788:10:
12-20 11:38:00.870 16116 16185 I RustStdoutStderr: called `Result::unwrap()` on an `Err` value: JavaException
12-20 11:38:00.870 16116 16185 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
12-20 11:38:00.872 16116 16186 E AndroidRuntime: FATAL EXCEPTION: Thread-2
12-20 11:38:00.872 16116 16186 E AndroidRuntime: Process: com.example.Testing, PID: 16116
12-20 11:38:00.872 16116 16186 E AndroidRuntime: java.lang.NoSuchMethodError: no non-static method "Landroid/view/WindowManagerImpl;.getCurrentWindowMetrics()Landroid/view/WindowMetrics;"
12-20 11:38:00.876   966  1076 W ActivityManager:   Force finishing activity com.example.Testing/dev.dioxus.main.MainActivity
```


Using Tao 0.31.0 with dioxus:
```

12-20 11:51:57.803 17664 17664 D Surface : Surface::allocateBuffers(this=0x81313000)
12-20 11:51:57.803 17664 17719 D Surface : Surface::connect(this=0x81313000,api=1)
12-20 11:51:57.803   487  1063 I BufferQueueProducer: [bitpit.launcher/bitpit.launcher.ui.HomeActivity#0](this:0xb0b6b000,id:4083,api:1,p:17664,c:487) connect(P): api=1 producer=(17664:bitpit.launcher) producerControlledByApp=true
12-20 11:51:57.805   487   487 I BufferQueueConsumer: [Splash Screen com.example.Testapp#0](this:0xaec99000,id:4103,api:2,p:-1,c:-1) disconnect(C)
12-20 11:51:57.806   487   487 I BufferQueue: [Splash Screen com.example.Testapp#0](this:0xaec99000,id:4103,api:2,p:-1,c:-1) ~BufferQueueCore
12-20 11:51:57.816   487   536 I BufferQueueProducer: [NavigationBar#0](this:0xb292e000,id:4079,api:1,p:1142,c:487) queueBuffer: fps=34.19 dur=1316.13 max=561.34 min=10.34
12-20 11:51:57.822   487   536 I BufferQueueProducer: [StatusBar#0](this:0xb0143000,id:4,api:1,p:1142,c:487) queueBuffer: fps=0.76 dur=1314.45 max=1314.45 min=1314.45
12-20 11:51:57.824   966  1214 I WindowManager: Relayout Window{ec79086 u0 com.example.Testapp/dev.dioxus.main.MainActivity}: oldVis=4 newVis=0 focusMayChange = true
12-20 11:51:57.830 17664 17664 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@bb8860f, this = DecorView@28af370[HomeActivity]
12-20 11:51:57.854   466   493 I vendor.mediatek.hardware.power@2.0-impl: powerHintAsync hint:8, data:0
12-20 11:51:57.861   487   534 I BufferQueueProducer: [bitpit.launcher/bitpit.launcher.ui.HomeActivity#0](this:0xb0b6b000,id:4083,api:1,p:17664,c:487) queueBuffer: fps=0.09 dur=22745.56 max=22630.21 min=115.34
12-20 11:51:57.861   966   979 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-20 11:51:57.861   966   979 I PowerWrap: PowerHal_Wrap_querySysInfo
12-20 11:51:57.864   966   979 E PowerHalWrapper: <amsBoostStop> duration: 6000ms
12-20 11:51:57.864   966   979 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-20 11:51:57.864   966   979 I PowerWrap: PowerHal_Wrap_mtkPowerHint
12-20 11:51:57.874 24122 24122 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@278a7b3, this = DecorView@7ea2170[MainActivity]
12-20 11:51:57.882 24122 24160 I RustStdoutStderr: thread 'main' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/cell.rs:1272:14:
12-20 11:51:57.882 24122 24160 I RustStdoutStderr: already borrowed: BorrowMutError
12-20 11:51:57.882 24122 24160 I RustStdoutStderr: thread 'main' panicked at library/core/src/panicking.rs:221:5:
12-20 11:51:57.882 24122 24160 I RustStdoutStderr: panic in a function that cannot unwind
12-20 11:51:57.882 24122 24160 I RustStdoutStderr: stack backtrace:
12-20 11:51:57.882 24122 24160 I RustStdoutStderr:    0: 0x87458cf8 - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    1: 0x874766f6 - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    2: 0x874511f0 - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    3: 0x8745a6d4 - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    4: 0x8745a35a - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    5: 0x8745b06c - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    6: 0x8745ae48 - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    7: 0x8745904c - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    8: 0x8745ac2e - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:    9: 0x87473b74 - <unknown>
12-20 11:51:57.883 24122 24160 I RustStdoutStderr:   10: 0x87473bce - <unknown>

```

the ruststdout errer goes on forvere until i press the "close app" button in the "Testapp keys stopping" window

**Comment by waozixyz** [comment]
@jkelleyrtp regarding your suggestion to try running tauri with the older version of tao that dioxus uses.

i did that as well. forked all the tao tauri projects, changed the dependency to the version in question 0.30.0, and made sure cargo.lock is using that version.

running it works fine as always, so seems be some kind of difference between how tauri and dioxus leverage tao?

what else can I try to analyze/ debug?

**Comment by agorges** [comment]
The problem is in tao (https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/android/mod.rs#L791 line 791) the call to **getCurrentWindowMetrics** which was introduces at api level 30 (Android 11).
As soon as I have a working patch (it can take a couple of days) I will open a pull request (tao) and post a workaround here.


If you need a solution right now clone tao, checkout the tag for the used version (cargo tree -e all | grep tao) and fix the function: **pub fn size(&self) -> PhysicalSize<u32>**  to use the old method on old devices.

In the Cargo.toml of your project add the following lines to use your local copy of tao. change the path accordingly

```toml
[patch.crates-io]
tao = { path = "../tao" }
```

**Comment by waozixyz** [comment]
thank you for the update!

**Comment by MarkGordeychuk** [comment]
@agorges I had a similar problem, and your solution helped me fix it.

I'll leave the code for the `size` function here. I'm not very good at this and used AI to help me write this function, so there may be some inaccuracies in the code, but it works nonetheless.

<details>

<summary>Code</summary>

```Rust
impl MonitorHandle {
  ...
  pub fn size(&self) -> PhysicalSize<u32> {
    // TODO decide how to get JNIENV
    if let Some(w) = ndk_glue::window_manager().as_ref() {
      let ctx = ndk_context::android_context();
      let vm = unsafe { jni::JavaVM::from_raw(ctx.vm().cast()) }.unwrap();
      let mut env = vm.attach_current_thread().unwrap();

      // Get Android SDK Version
      let sdk_int = {
        let version_class = env
          .find_class("android/os/Build$VERSION")
          .unwrap();

        env.get_static_field(version_class, "SDK_INT", "I")
          .unwrap()
          .i()
          .unwrap() as i32
      };
      
      let window_manager = w.as_obj();
      if sdk_int >= 30 {
        // API level >= 30
        let metrics = env
          .call_method(
            window_manager,
            "getCurrentWindowMetrics",
            "()Landroid/view/WindowMetrics;",
            &[],
          )
          .unwrap()
          .l()
          .unwrap();
        let rect = env
          .call_method(&metrics, "getBounds", "()Landroid/graphics/Rect;", &[])
          .unwrap()
          .l()
          .unwrap();
        let width = env
          .call_method(&rect, "width", "()I", &[])
          .unwrap()
          .i()
          .unwrap();
        let height = env
          .call_method(&rect, "height", "()I", &[])
          .unwrap()
          .i()
          .unwrap();
        PhysicalSize::new(width as u32, height as u32)
      } else {
        // API level < 30
        let display = env
          .call_method(
            window_manager,
            "getDefaultDisplay",
            "()Landroid/view/Display;",
            &[]
          )
          .unwrap()
          .l()
          .unwrap();
        let point = env
          .new_object("android/graphics/Point", "()V", &[])
          .unwrap();
        env
          .call_method(&display, "getSize", "(Landroid/graphics/Point;)V", &[(&point).into()])
          .unwrap();
        let width = env
          .get_field(&point, "x", "I")
          .unwrap()
          .i()
          .unwrap();
        let height = env
          .get_field(&point, "y", "I")
          .unwrap()
          .i()
          .unwrap();
        PhysicalSize::new(width as u32, height as u32)
      }
    } else {
      PhysicalSize::new(0, 0)
    }
  }
  ...
}
```

</details>
