### ISSUE TITLE
Support for the armv7-linux-androideabi target was dropped starting with Dioxus 0.7.4

### ISSUE THREAD

**Issue by atty303** [DioxusLabs/dioxus#5637]
**Problem**

Up to Dioxus 0.7.3, building and running on 32-bit Android targets worked correctly. Starting with 0.7.4, the following compilation error is emitted:

```
   2.418s  INFO  error: Only 64-bit Android targets are supported
   --> /Users/a13400/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/manganis-0.7.9/src/android/callback.rs:122:5
    |
122 |     compile_error!("Only 64-bit Android targets are supported");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This check was introduced in #4842.

While 32-bit Android is largely obsolete on smartphones, it is still actively used on devices such as Sony Android TVs and various Android-based set-top boxes (STBs). I would appreciate continued support for this target.

In my case, support for 32-bit Android is a hard requirement, so I am currently unable to upgrade beyond Dioxus 0.7.3.

**Steps To Reproduce**

- `dx bundle --android --release --target armv7-linux-androideabi`

**Expected behavior**

The project should build successfully for 32-bit Android targets (armv7-linux-androideabi), as it did prior to Dioxus 0.7.4.

**Environment:**

- Dioxus version: 0.7.9
- Rust version: 1.93.1
- OS: macOS
- App platform: Android

**Questionnaire**

I don't have time to fix this right now, but maybe later.

**Comment by ealmloff** [comment]
That specific gate could probably be replaced with `usize` to match the system pointer width. If ffi relies on 64 bit pointers elsewhere, gating the ffi module by pointer width would be better than a compile error since the rest of the asset system is pointer width independant
